name: tiles_gallery
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutterwear:
    path: ../../packages/wear
  http: any
  fl_chart: ^0.66.2
  widgets_to_image: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

tiles:
  WeatherTile:
    label: Quick Weather
    preview: assets/weather/forecast_sunny.png
  TimerTile:
    label: Timers
  CryptoTile:
    label: Crypto Price
  TestTile:
    label: Test Tile
  FitnessTile:
    label: Fitness

flutter:
  uses-material-design: true
  assets:
    - assets/weather/
    - assets/crypto/
    - assets/smarthome/
    - assets/fitness/