name: wear_example
description: "Demonstrates how to use the wear plugin."
publish_to: 'none' 

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wear:
    path: ../../src
  
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  build: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

tiles:
  ExampleTile:
    label: Example Tile
    preview: assets/check.png

flutter:
  uses-material-design: true
  assets:
    - assets/
