name: flutterwear
description: "A one-stop shop for all things related to Wear OS."
homepage: https://github.com/yoeden/flutter_wear
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  xml: ^6.5.0
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Needed by build_version
  build_runner: 2.3.3
  # https://pub.dev/packages/build_version
  build_version: 2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: yoeden.flutter.wear
        pluginClass: WearPlugin